### ISSUE TITLE
Admin stuff

### ISSUE THREAD

**Issue by nicologreggio** [nicologreggio/solid-funicular#2]

**Comment by AlbertoSinigaglia** [comment]
## To do

- [x] Login
- [ ] Homepage con le richieste
- [ ] Pagina visualizzazione richiesta
- [x] Pagina errore (guardare funzione `error`)
---
Prodotti
- [x] C.
- [x] R.
- [x] U.
- [x] D.
---
Categorie
- [x] C.
- [x] R.
- [x] U.
- [x] D.
---
Materiali
- [x] C.
- [x] R.
- [x] U.
- [x] D.
- [x] Aggiunta selezione materiali su C/D di prodotti
---
##  Opzionali per la fine se avanza tempo

Commenti (opzionale per la fine se avanza tempo)
- [ ] C.
- [ ] R.
- [ ] U.
- [ ] D.
